Repository nakjun12/seo-blog, pull requests merged in 2024-06, with the labels that each got.

#61 [fix] 카테고리 오류 수정
  posts/next/example.mdx
  posts/next/nextjs-env.mdx
  posts/react/example.mdx
  posts/react/mdtest.mdx
  src/feature/desktop-category/desktop-category.tsx
  src/feature/mobile-category/mobile-category.tsx
  src/feature/open-category/open-category.tsx
  src/feature/open-menu/open-menu.tsx
  src/widgets/header/header.tsx
Labels: 🛠Fix

#68 [fix] breadcrumb 수정
  src/_pages/post/post.page.tsx
  src/feature/desktop-category/desktop-category.tsx
  src/shared/common-ui/breadcrumb/breadcrumb.tsx
  src/widgets/footer/footer.tsx
Labels: :computer: 태크니컬 SEO, 🛠Fix

#67 [fix] 월요일 블로그 글 업로드 및 vscode 수정
  .vscode/extensions.json
  .vscode/mdx.code-snippets
  .vscode/settings.json
  posts/next/example.mdx
  posts/react/css-library-comparison.mdx
  posts/react/mdtest.mdx
  public/css-logo.png
  public/example-mdx/example.mdx
Labels: :book: 콘텐츠 SEO, 🛠Fix

#70 [feat] html이란 무엇인가 포스팅 작성 & author-foot 마진 간격 조정
  posts/html/what-is-html.mdx
  public/html.webp
  src/entities/posts/ui/post-author-foot.tsx
Labels: :book: 콘텐츠 SEO

#74 [feat] 개발 과정에서 글 작성 시 AutoRefresh 기능 추가
  .vscode/settings.json
  app/auto-refresh.js
  app/layout.tsx
  package.json
  pnpm-lock.yaml
  posts/next/nextjs-env.mdx
  watcher.cjs
Labels: 😎Feat, 🛠Fix

#76 [fix] robots.ts , sitemap.ts next 구성요소로 이동
  app/robots.ts
  app/sitemap.ts
Labels: 🛠Fix

#77 Feat/table of content
  src/entities/posts/lib/utils/toc.util.ts
  src/shared/common-ui/toc/toc.tsx
Labels: 🛠Fix

#79 [fix] 여러가지 이슈 수정
  app/(posts)/[...slug]/layout.tsx
  pnpm-lock.yaml
  src/_pages/post/post.page.tsx
  src/entities/posts/lib/utils/time.util.ts
  src/entities/posts/lib/utils/toc.util.ts
  src/entities/posts/model/post.ts
  src/entities/posts/ui/post-author-head.tsx
  src/feature/desktop-category/desktop-category.tsx
  src/feature/mobile-category/mobile-category.tsx
  src/feature/open-category/open-category.tsx
  src/feature/open-menu/open-menu.tsx
  src/shared/stores/toggle-menu.ts
  src/widgets/header/header.tsx
Labels: 🛠Fix

#80 [fix] mdx 파일 일괄 수정
  posts/html/what-is-html.mdx
  posts/react/css-library-comparison.mdx
  posts/react/react-error-handling.mdx
  src/entities/posts/lib/utils/toc.util.ts
  src/shared/common-ui/toc/toc.tsx
Labels: 🛠Fix

#82 [feat] post title image 추가
  src/_pages/post/post.page.tsx
  src/entities/posts/ui/post-author-head.tsx
  src/entities/posts/ui/post-card.tsx
  src/entities/posts/ui/post-title-image.tsx
  src/shared/common-ui/mdx/mdx-remote.tsx
Labels: 😎Feat

#83 [feat] home 페이지 추천글 추가
  src/_pages/home/home.page.tsx
  src/entities/posts/ui/recommend-post.tsx
  src/shared/common-ui/toc/toc.tsx
  tailwind.config.ts
Labels: 😎Feat

#86 [ feat ] 아티클 작성 + 릴리즈데이트 안된 글 프로덕션에서 가리는 처리 추가
  posts/next/nextjs-env.mdx
  posts/next/nextjs-tailwindcss.mdx
  posts/programming/editor-recommend-for-developer.mdx
  posts/react/how-to-make-react-calendar.mdx
  posts/react/react-redux.mdx
  posts/typescript/typescript-utility-type.mdx
  public/posts/how-to-make-react-calendar-1.webp
  src/entities/posts/lib/utils/time.util.ts
  src/entities/posts/model/post.ts
  src/shared/config/environment.ts
Labels: :book: 콘텐츠 SEO, 😎Feat

#88 fix: isReleased 판단 오류 수정
  src/entities/posts/lib/utils/post.util.ts
  src/entities/posts/lib/utils/time.util.ts
Labels: 🛠Fix

#89 [feat] post top toc 추가
  src/_pages/post/post.page.tsx
  src/shared/common-ui/mdx/mdx-remote.tsx
  src/shared/common-ui/side-toc/side-toc.tsx
  src/shared/common-ui/top-toc/top-toc.tsx
Labels: 😎Feat

#90 [fix] sitemap category 누락 수정
  app/sitemap.ts
Labels: 🛠Fix

#92 feat: json-ld 추가 (블로그 개별 포스팅& layout 전체에 website추가) 및 글 수정
  app/layout.tsx
  posts/html/how-to-make-web-page.mdx
  posts/html/what-is-html.mdx
  src/_pages/post/post.page.tsx
  src/shared/json-ld/json-ld.tsx
Labels: 😎Feat

#96 feat: 길종 글에 대한 썸네일 일괄 추가
  posts/next/nextjs-env.mdx
  posts/next/nextjs-tailwindcss.mdx
  posts/programming/editor-recommend-for-developer.mdx
  posts/react/how-to-make-react-calendar.mdx
  posts/react/react-redux.mdx
  posts/typescript/typescript-utility-type.mdx
  public/thumbnail-calendar.webp
  public/thumbnail-editor.webp
  public/thumbnail-nextjs-env.webp
  public/thumbnail-redux.webp
  public/thumbnail-tailwindcss.webp
  public/thumbnail-typescript.webp
Labels: :book: 콘텐츠 SEO, 🛠Fix

#97 feat: 포스트 발행 및 글 제목 수정
  posts/html/how-to-make-web-page.mdx
  posts/html/html-layout-tag-and-id-calss-property.mdx
  posts/html/what-is-html.mdx
  public/html-class-example.webp
  public/html-id-example.webp
  public/html-layout.webp
  public/website-layout.webp
Labels: :book: 콘텐츠 SEO

#98 mod: mdx 파일 writeDate & releaseDate 수정
  posts/html/how-to-make-web-page.mdx
  posts/html/html-layout-tag-and-id-calss-property.mdx
  posts/html/what-is-html.mdx
Labels: 🛠Fix

#99 [feat] 온라인 ide 추천글 작성
  posts/programming/online-ide-recommend-for-developer.mdx
  public/code-pen-1.webp
  public/code-pen-2.webp
  public/goorm-ide-1.webp
  public/goorm-ide-2.webp
  public/ide-one.webp
  public/ryugod.webp
  public/top-ide.webp
Labels: :book: 콘텐츠 SEO
