Repository nakjun12/seo-blog, pull requests merged in 2024-05, with the labels that each got.

#40 feat: header 추가
  app/layout.tsx
  src/shared/common-ui/progress-bar/progress-bar.tsx
  src/widgets/header/header.tsx
Labels: 😎Feat

#41 feat: progress bar header에 추가
  src/widgets/header/header.tsx
Labels: 😎Feat

#42 feat: posts 메타데이터 추가
  app/(posts)/posts/[slug]/page.tsx
  app/(posts)/posts/page.tsx
  app/layout.tsx
  src/entities/posts/lib/utils/post.util.ts
Labels: :computer: 태크니컬 SEO, 😎Feat

#43 feat: footer 추가
  app/layout.tsx
  src/widgets/footer/footer.tsx
Labels: 😎Feat

#44 feat: favicon 추가
  app/favicon.ico
  app/layout.tsx
  public/favicon/apple-touch-icon-114x114.png
  public/favicon/apple-touch-icon-120x120.png
  public/favicon/apple-touch-icon-144x144.png
  public/favicon/apple-touch-icon-152x152.png
  public/favicon/apple-touch-icon-57x57.png
  public/favicon/apple-touch-icon-72x72.png
  public/favicon/favicon.ico
  public/favicon/icon-16x16.png
  public/favicon/icon-196x196.png
  public/favicon/icon-32x32.png
  public/favicon/icon-48x48.png
  public/favicon/msapplication-tile.png
  public/next.svg
  public/vercel.svg
  src/shared/icons/favicons.ts
Labels: 😎Feat

#46 feat: breadcrumb 구조화 데이터 json-ld로 적용
  src/shared/common-ui/breadcrumb/breadcrumb.tsx
Labels: :computer: 태크니컬 SEO, 😎Feat

#51 [feat] 햄버거 버튼 구현 & 프로그레스바 폭 수정
  src/feature/open-menu/index.ts
  src/feature/open-menu/open-menu.tsx
  src/shared/common-ui/progress-bar/progress-bar.tsx
  src/widgets/header/header.tsx
Labels: 🎨Style

#52 [fix] 브레드크럼 json-LD 수정
  app/(posts)/posts/page.tsx
  src/shared/common-ui/breadcrumb/breadcrumb.tsx
Labels: :computer: 태크니컬 SEO, 🛠Fix

#53 [fix] 브레드크럼 json-LD url 절대 경로로 수정
  app/test/page.tsx
  src/_pages/Test/test.page.tsx
  src/shared/common-ui/breadcrumb/breadcrumb.tsx
Labels: :computer: 태크니컬 SEO, 🛠Fix

#54 [fix] 브레드크럼 json-LD url 경로 수정
  src/shared/common-ui/breadcrumb/breadcrumb.tsx
Labels: :computer: 태크니컬 SEO, 🛠Fix

#55 [fix] posts 페이지 제거
  app/(posts)/[...slug]/layout.tsx
  app/(posts)/[...slug]/page.tsx
  app/(posts)/[slug]/page.tsx
  app/(posts)/layout.tsx
  app/(posts)/posts/page.tsx
  app/page.tsx
  src/_pages/home/home.page.tsx
  src/_pages/posts/posts.page.tsx
  src/entities/posts/lib/utils/post.util.ts
  src/entities/posts/ui/post-card.tsx
  src/widgets/header/header.tsx
Labels: :computer: 태크니컬 SEO, 🛠Fix

#58 [feat] 햄버거 메뉴 추가
  app/layout.tsx
  package.json
  pnpm-lock.yaml
  posts/Next/example.mdx
  posts/Next/nextjs-env.mdx
  posts/React/example.mdx
  posts/React/mdtest.mdx
  src/_pages/posts/posts.page.tsx
  src/entities/posts/lib/utils/language.util.ts
  src/entities/posts/model/post.ts
  src/feature/index.ts
  src/feature/mobile-category/index.ts
  src/feature/mobile-category/mobile-category.tsx
  src/feature/open-menu/open-menu.tsx
  src/shared/stores/index.ts
  src/shared/stores/toggle-menu.ts
  src/widgets/header/header.tsx
Labels: 😎Feat

#60 [fix] desktop category 스크롤 금지 수정
  src/feature/desktop-category/desktop-category.tsx
Labels: 🛠Fix
